### ISSUE TITLE
Error unknown option: --separator=

### ISSUE THREAD

**Issue by avucic** [lvim-tech/lvim-fm#3]
Hi,
I wanted to try the plugin with default settings but after I run command:

`LvimFileManager `
I can see print loop with this error

`unknown option: --separator=`
Am I missing something?

nvim 0.9.0
MacOS

**Comment by lvim-tech** [comment]
Fzf version?

**Comment by avucic** [comment]
> Fzf version?

0.30.0 (2093667)

**Comment by avucic** [comment]
Ah my bad...I see now it's outdated...I updated to 0.41 and now works fine
